
project_id = "wykysgikszfhpblaygpr"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[analytics]
enabled = false

[experimental]
multiservice = true

[functions.gemini-api]
verify_jwt = true
